// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuzAchIHNyH-iEL-0aYImLp_t_vCa9rRU',
    appId: '1:62057288644:web:e2452af9d3051bedd74a91',
    messagingSenderId: '62057288644',
    projectId: 'foodies-25317',
    authDomain: 'foodies-25317.firebaseapp.com',
    databaseURL: 'https://foodies-25317.firebaseio.com',
    storageBucket: 'foodies-25317.appspot.com',
    measurementId: 'G-FG669D56ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW4HlmXH0mxokquxPJ3sfaVZq6Tv259CY',
    appId: '1:62057288644:android:017bc3966bbafe28d74a91',
    messagingSenderId: '62057288644',
    projectId: 'foodies-25317',
    databaseURL: 'https://foodies-25317.firebaseio.com',
    storageBucket: 'foodies-25317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBYtNPKJxD85DfIhaNxEaNz6l8GGbx1A',
    appId: '1:62057288644:ios:b2bfdd8a857c9a9ad74a91',
    messagingSenderId: '62057288644',
    projectId: 'foodies-25317',
    databaseURL: 'https://foodies-25317.firebaseio.com',
    storageBucket: 'foodies-25317.appspot.com',
    iosClientId: '62057288644-gqgs139pk3i09kiplcs6hgphefjdlhbf.apps.googleusercontent.com',
    iosBundleId: 'io.initappz.foodies.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPBYtNPKJxD85DfIhaNxEaNz6l8GGbx1A',
    appId: '1:62057288644:ios:b2d77fd51f3303bad74a91',
    messagingSenderId: '62057288644',
    projectId: 'foodies-25317',
    databaseURL: 'https://foodies-25317.firebaseio.com',
    storageBucket: 'foodies-25317.appspot.com',
    iosClientId: '62057288644-k1sd8p21h2lpf0m4gvdm7fo24tv875kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodiesVendors',
  );
}
